### ISSUE TITLE
Ошибка в скрипте

### ISSUE THREAD

**Issue by das13** [kostyansasha/Lab3_BookShop#4]
В скрипте
ALTER TABLE "CONTENR_ORDER" ADD CONSTRAINT "CONTENR_ORDER_ORDER_FK" 
FOREIGN KEY ("ID_ORDER")
REFERENCES ."ORDERS" ("ID_ORDER") ON DELETE CASCADE ENABLE;
есть лишняя точка перед **"ORDERS"**

**Comment by oleksandr-kostian** [comment]
Issue is corrected. e1e221c23f3eb3ad0e158a042c614a86163abc7d
